In [1]:
# importing libraries
import pandas as pd
import numpy as np

In [2]:
# load datasets
i_cols = ['movie_id', 'movie_title' ,'release_date','video_release_date', 'IMDb_URL', 'unknown', 'Action', 'Adventure',
'Animation', 'Children\'s', 'Comedy', 'Crime', 'Documentary', 'Drama', 'Fantasy',
'Film-Noir', 'Horror', 'Musical', 'Mystery', 'Romance', 'Sci-Fi', 'Thriller', 'War', 'Western']
movies = pd.read_csv('u.item', sep='|', names=i_cols,
encoding='latin-1')

ratings = pd.read_csv("u.data", sep="\t",
                      names=["user_id","movie_id","rating","timestamp"])

In [3]:
movies

,movie_id,movie_title,release_date,video_release_date,IMDb_URL,unknown,Action,Adventure,Animation,Children's,...,Fantasy,Film-Noir,Horror,Musical,Mystery,Romance,Sci-Fi,Thriller,War,Western
0,1,Toy Story (1995),01-Jan-1995,NaN,http://us.imdb.com/M/title-exact?Toy%20Story%2...,0,0,0,1,1,...,0,0,0,0,0,0,0,0,0,0
1,2,GoldenEye (1995),01-Jan-1995,NaN,http://us.imdb.com/M/title-exact?GoldenEye%20(...,0,1,1,0,0,...,0,0,0,0,0,0,0,1,0,0
2,3,Four Rooms (1995),01-Jan-1995,NaN,http://us.imdb.com/M/title-exact?Four%20Rooms%...,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
3,4,Get Shorty (1995),01-Jan-1995,NaN,http://us.imdb.com/M/title-exact?Get%20Shorty%...,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,5,Copycat (1995),01-Jan-1995,NaN,http://us.imdb.com/M/title-exact?Copycat%20(1995),0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1677,1678,Mat' i syn (1997),06-Feb-1998,NaN,http://us.imdb.com/M/title-exact?Mat%27+i+syn+...,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1678,1679,B. Monkey (1998),06-Feb-1998,NaN,http://us.imdb.com/M/title-exact?B%2E+Monkey+(...,0,0,0,0,0,...,0,0,0,0,0,1,0,1,0,0
1679,1680,Sliding Doors (1998),01-Jan-1998,NaN,http://us.imdb.com/Title?Sliding+Doors+(1998),0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
1680,1681,You So Crazy (1994),01-Jan-1994,NaN,http://us.imdb.com/M/title-exact?You%20So%20Cr...,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1681,1682,Scream of Stone (Schrei aus Stein) (1991),08-Mar-1996,NaN,http://us.imdb.com/M/title-exact?Schrei%20aus%...,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [4]:
ratings

       user_id  movie_id  rating  timestamp
0          196       242       3  881250949
1          186       302       3  891717742
2           22       377       1  878887116
3          244        51       2  880606923
4          166       346       1  886397596
...        ...       ...     ...        ...
99995      880       476       3  880175444
99996      716       204       5  879795543
99997      276      1090       1  874795795
99998       13       225       2  882399156
99999       12       203       3  879959583

[100000 rows x 4 columns]

In [5]:
# compute rating stats
movie_stats = ratings.groupby("movie_id").agg(
    avg_rating=("rating","mean"),
    num_ratings=("rating","count")
).reset_index()

In [6]:
movie_stats

      movie_id  avg_rating  num_ratings
0            1    3.878319          452
1            2    3.206107          131
2            3    3.033333           90
3            4    3.550239          209
4            5    3.302326           86
...        ...         ...          ...
1677      1678    1.000000            1
1678      1679    3.000000            1
1679      1680    2.000000            1
1680      1681    3.000000            1
1681      1682    3.000000            1

[1682 rows x 3 columns]

In [7]:
# merge
df = movies.merge(movie_stats, on="movie_id")

In [8]:
df

,movie_id,movie_title,release_date,video_release_date,IMDb_URL,unknown,Action,Adventure,Animation,Children's,...,Horror,Musical,Mystery,Romance,Sci-Fi,Thriller,War,Western,avg_rating,num_ratings
0,1,Toy Story (1995),01-Jan-1995,NaN,http://us.imdb.com/M/title-exact?Toy%20Story%2...,0,0,0,1,1,...,0,0,0,0,0,0,0,0,3.878319,452
1,2,GoldenEye (1995),01-Jan-1995,NaN,http://us.imdb.com/M/title-exact?GoldenEye%20(...,0,1,1,0,0,...,0,0,0,0,0,1,0,0,3.206107,131
2,3,Four Rooms (1995),01-Jan-1995,NaN,http://us.imdb.com/M/title-exact?Four%20Rooms%...,0,0,0,0,0,...,0,0,0,0,0,1,0,0,3.033333,90
3,4,Get Shorty (1995),01-Jan-1995,NaN,http://us.imdb.com/M/title-exact?Get%20Shorty%...,0,1,0,0,0,...,0,0,0,0,0,0,0,0,3.550239,209
4,5,Copycat (1995),01-Jan-1995,NaN,http://us.imdb.com/M/title-exact?Copycat%20(1995),0,0,0,0,0,...,0,0,0,0,0,1,0,0,3.302326,86
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1677,1678,Mat' i syn (1997),06-Feb-1998,NaN,http://us.imdb.com/M/title-exact?Mat%27+i+syn+...,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1.000000,1
1678,1679,B. Monkey (1998),06-Feb-1998,NaN,http://us.imdb.com/M/title-exact?B%2E+Monkey+(...,0,0,0,0,0,...,0,0,0,1,0,1,0,0,3.000000,1
1679,1680,Sliding Doors (1998),01-Jan-1998,NaN,http://us.imdb.com/Title?Sliding+Doors+(1998),0,0,0,0,0,...,0,0,0,1,0,0,0,0,2.000000,1
1680,1681,You So Crazy (1994),01-Jan-1994,NaN,http://us.imdb.com/M/title-exact?You%20So%20Cr...,0,0,0,0,0,...,0,0,0,0,0,0,0,0,3.000000,1
1681,1682,Scream of Stone (Schrei aus Stein) (1991),08-Mar-1996,NaN,http://us.imdb.com/M/title-exact?Schrei%20aus%...,0,0,0,0,0,...,0,0,0,0,0,0,0,0,3.000000,1

In [9]:
# filter movies with at least 50 ratings
df = df[df["num_ratings"] >= 50]

In [10]:
df

,movie_id,movie_title,release_date,video_release_date,IMDb_URL,unknown,Action,Adventure,Animation,Children's,...,Horror,Musical,Mystery,Romance,Sci-Fi,Thriller,War,Western,avg_rating,num_ratings
0,1,Toy Story (1995),01-Jan-1995,NaN,http://us.imdb.com/M/title-exact?Toy%20Story%2...,0,0,0,1,1,...,0,0,0,0,0,0,0,0,3.878319,452
1,2,GoldenEye (1995),01-Jan-1995,NaN,http://us.imdb.com/M/title-exact?GoldenEye%20(...,0,1,1,0,0,...,0,0,0,0,0,1,0,0,3.206107,131
2,3,Four Rooms (1995),01-Jan-1995,NaN,http://us.imdb.com/M/title-exact?Four%20Rooms%...,0,0,0,0,0,...,0,0,0,0,0,1,0,0,3.033333,90
3,4,Get Shorty (1995),01-Jan-1995,NaN,http://us.imdb.com/M/title-exact?Get%20Shorty%...,0,1,0,0,0,...,0,0,0,0,0,0,0,0,3.550239,209
4,5,Copycat (1995),01-Jan-1995,NaN,http://us.imdb.com/M/title-exact?Copycat%20(1995),0,0,0,0,0,...,0,0,0,0,0,1,0,0,3.302326,86
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1064,1065,Koyaanisqatsi (1983),01-Jan-1983,NaN,http://us.imdb.com/M/title-exact?Koyaanisqatsi...,0,0,0,0,0,...,0,0,0,0,0,0,1,0,3.490566,53
1072,1073,Shallow Grave (1994),01-Jan-1994,NaN,http://us.imdb.com/Title?Shallow+Grave+(1994),0,0,0,0,0,...,0,0,0,0,0,1,0,0,3.818182,66
1073,1074,Reality Bites (1994),01-Jan-1994,NaN,http://us.imdb.com/M/title-exact?Reality%20Bit...,0,0,0,0,0,...,0,0,0,0,0,0,0,0,2.961039,77
1100,1101,Six Degrees of Separation (1993),01-Jan-1993,NaN,http://us.imdb.com/M/title-exact?Six%20Degrees...,0,0,0,0,0,...,0,0,1,0,0,0,0,0,3.770270,74
1118,1119,Some Kind of Wonderful (1987),01-Jan-1987,NaN,http://us.imdb.com/M/title-exact?Some%20Kind%2...,0,0,0,0,0,...,0,0,0,1,0,0,0,0,3.661017,59

In [11]:
# list of genre column indexes (last 19 columns)
genre_cols = movies.columns[-18:]

In [12]:
genre_cols

Index(['Action', 'Adventure', 'Animation', 'Children's', 'Comedy', 'Crime',
       'Documentary', 'Drama', 'Fantasy', 'Film-Noir', 'Horror', 'Musical',
       'Mystery', 'Romance', 'Sci-Fi', 'Thriller', 'War', 'Western'],
      dtype='object')

In [13]:
# Print top 5 movie names under each genre
for genre in genre_cols:
    movies_in_genre = df[df[genre] == 1].sort_values(
        by=["avg_rating","num_ratings"], ascending=False
    ).head(5)

    print(f"\n=== {genre} ===")
    for title in movies_in_genre['movie_title']:
        print(title)

=== Action ===
Star Wars (1977)
Godfather, The (1972)
Raiders of the Lost Ark (1981)
Titanic (1997)
Empire Strikes Back, The (1980)

=== Adventure ===
Star Wars (1977)
Raiders of the Lost Ark (1981)
Lawrence of Arabia (1962)
Empire Strikes Back, The (1980)
African Queen, The (1951)

=== Animation ===
Close Shave, A (1995)
Wrong Trousers, The (1993)
Wallace & Gromit: The Best of Aardman Animation (1996)
Grand Day Out, A (1992)
Toy Story (1995)

=== Children's ===
Wizard of Oz, The (1939)
Babe (1995)
Toy Story (1995)
E.T. the Extra-Terrestrial (1982)
Aladdin (1992)

=== Comedy ===
Close Shave, A (1995)
Wrong Trousers, The (1993)
North by Northwest (1959)
As Good As It Gets (1997)
Cinema Paradiso (1988)

=== Crime ===
Usual Suspects, The (1995)
Godfather, The (1972)
Godfather: Part II, The (1974)
L.A. Confidential (1997)
Fargo (1996)

=== Documentary ===
Hoop Dreams (1994)
Celluloid Closet, The (1995)
Crumb (1994)
Looking for Richard (1996)
Koyaanisqatsi (1983)

=== Drama ===
Schindler's List (1993)
Casablanca (1942)
Shawshank Redemption, The (1994)
12 Angry Men (1957)
Citizen Kane (1941)

=== Fantasy ===
E.T. the Extra-Terrestrial (1982)
Heavenly Creatures (1994)
20,000 Leagues Under the Sea (1954)
Jumanji (1995)
Mask, The (1994)

=== Film-Noir ===
Manchurian Candidate, The (1962)
Maltese Falcon, The (1941)
Sunset Blvd. (1950)
L.A. Confidential (1997)
Blade Runner (1982)

=== Horror ===
Psycho (1960)
Alien (1979)
Young Frankenstein (1974)
Shining, The (1980)
Birds, The (1963)

=== Musical ===
Wizard of Oz, The (1939)
Singin' in the Rain (1952)
This Is Spinal Tap (1984)
Blues Brothers, The (1980)
My Fair Lady (1964)

=== Mystery ===
Rear Window (1954)
Third Man, The (1949)
Vertigo (1958)
Maltese Falcon, The (1941)
Amadeus (1984)

=== Romance ===
Casablanca (1942)
Star Wars (1977)
Titanic (1997)
Empire Strikes Back, The (1980)
African Queen, The (1951)

=== Sci-Fi ===
Star Wars (1977)
Dr. Strangelove or: How I Learned to Stop Worrying and Love the Bomb (1963)
Empire Strikes Back, The (1980)
Blade Runner (1982)
Alien (1979)

=== Thriller ===
Close Shave, A (1995)
Rear Window (1954)
Usual Suspects, The (1995)
Third Man, The (1949)
Silence of the Lambs, The (1991)

=== War ===
Schindler's List (1993)
Casablanca (1942)
Star Wars (1977)
Dr. Strangelove or: How I Learned to Stop Worrying and Love the Bomb (1963)
Lawrence of Arabia (1962)

=== Western ===
High Noon (1952)
Butch Cassidy and the Sundance Kid (1969)
Magnificent Seven, The (1954)
Unforgiven (1992)
Good, The Bad and The Ugly, The (1966)